version: 0.1


phases:
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`

artifacts:
  files:
    - LineaIcons/*
    - README.md
    - bootstrap/*
    - buildspec.yml 
    - css/*
    - fonts/*
    - img/*
    - index.html
    - js/*
    - mail.php
